# Generated by Django 4.0.2 on 2022-04-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Sin categoria', on_delete=django.db.models.deletion.CASCADE, to='posts.category'),
        ),
    ]
